version: '2'

services:
  postgres:
    container_name: pc_db
    image: postgres:alpine
    expose:
      - '5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      APP_USER_NAME: photo_contest
      APP_USER_PASSWORD: bPiuRrTG8JtRFMiuB0
    volumes:
      - pc_pgdata:/var/lib/postgresql/data/pgdata
      - ./config/initdb:/docker-entrypoint-initdb.d:ro
    restart: always

  rails:
    container_name: pc_app
    image: vsuhachev/photo_contest
    links:
      - postgres
    expose:
      - 3000
    environment:
      - DB_HOST=postgres
      - DB_NAME=photo_contest
      - DB_USER=photo_contest
      - DB_PWD=bPiuRrTG8JtRFMiuB0
      - DB_POOL=12
      - WEB_CONCURRENCY=2
      - RAILS_MAX_THREADS=5
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=9d493de61ef092a04759c2b835c24ac0ecddf4cd4086513c2380c38ef5cf04ad0a755c26e6cdcb6a87dc1aeec921482071223f79840acb483762439c358fcf7f
    tmpfs:
      - /opt/app/tmp
    volumes:
      - pc_uploads:/opt/app/public/uploads
    restart: always

  nginx:
    container_name: pc_web
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - rails:ro
    links:
      - rails
    restart: always

volumes:
  pc_pgdata:
    driver: local
  pc_uploads:
    driver: local
