version: '2'

services:
  postgres:
    container_name: pc_db
    image: postgres:alpine
    expose:
      - '5432'
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pc_pgdata:/var/lib/postgresql/data/pgdata
    restart: always

  redis:
    container_name: pc_redis
    image: redis:alpine
    expose:
      - '6379'
    restart: always

  rails:
    container_name: pc_app
    image: vsuhachev/photo_contest
    links:
      - postgres
      - redis
    expose:
      - 3000
    env_file: .env
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
    tmpfs:
      - /opt/app/tmp
      - /opt/app/log
    volumes:
      - pc_uploads:/opt/app/public/uploads
    restart: always

  nginx:
    container_name: pc_web
    image: nginx:alpine
    ports:
      - '8000:80'
    tmpfs:
      - /var/cache/nginx
    volumes:
      - pc_uploads:/opt/app/public/uploads:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - rails
    restart: always

volumes:
  pc_pgdata:
    driver: local
  pc_uploads:
    driver: local
