#!/usr/bin/env bash

set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
    CREATE ROLE "${APP_USER_NAME}" WITH ENCRYPTED PASSWORD '${APP_USER_PASSWORD}' LOGIN;
    CREATE DATABASE "${APP_DB:-$APP_USER_NAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${APP_DB:-$APP_USER_NAME}" TO "${APP_USER_NAME}";
EOSQL
